### ISSUE TITLE
Evaluating julia's speedup

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2016-cw5#14]
How should we evaluate julia's speedup when doing CPU, OpenCL, and more optimizations? The input c is randomized every time, and _sometimes_ it takes forever if the while loops run for a long time.

This makes it difficult to benchmark the improvements I've made - is it wrong to hardcode a value of c just to benchmark?

**Comment by m8pple** [comment]
The intrinsic variability of the problem is deliberate, as some workloads are highly
data-dependent.

So hard-coding c would probably be a bad idea - you want to test the bad cases and
the good (though particularly the bad).

Note that you have the ability to generate workloads of a fixed difficulty, as
you have the ability to generate fixed inputs (create_puzzle_input) then store
them as a file. That input can then be played back through many different
implementations, always of the same hardness. It's also a good way of
calibrating improvement over time, by capturing a selection of "golden"
inputs.

**Comment by jeremych1000** [comment]
Thanks, didn't look at create_puzzle_input.
