### ISSUE TITLE
Unsure about the meaning of this sentence...

### ISSUE THREAD

**Issue by awai54st** [HPCE/hpce-2016-cw5#2]
Hi,

In the description you mentioned:

"Anything in the include directory is not owned by you, and subject to change
Any changes will happen in an additive way (none are expected for this CW)"

Sorry but I'm not sure if I understand the meaning of this. So are we supposed to change codes in the include directory or not? Cos it appears that there are lots of computations there...

Thank you
Best, awai54st

**Comment by mattinmir** [comment]
As far as I understand, that means don't touch the include directory, but I don't see where else there is something we can actually work with

Does @m8pple perhaps mean the `include/puzzler/core` directory is not to be touched, rather than the entire `include`?

**Comment by m8pple** [comment]
The part you can change is in the `provider` directory.

If you look at the way it builds `lib/libpuzzler.a`, it compiles the
source and headers from `provider`, which provide the actual
implementations. The implementations in the `include` directory
should not be changed - the main reason I try to enforce this
is so that people don't destroy their ability to compare against
a known good version (this often happens when people modify
in place). There is a slight possibility that I might need to patch
it as well, so I'd like to keep it clean.

I'll add a note pointing people towards the provider directory.
